# Generated by Django 3.2.8 on 2021-11-17 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vibrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is room private'),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='roommember',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='current_members',
            field=models.ManyToManyField(blank=True, related_name='room', to='vibrate.RoomMember'),
        ),
    ]
