# Generated by Django 3.2.8 on 2021-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibrate', '0002_roommember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.CharField(default='aassasassa', max_length=24, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
