# Generated by Django 3.2.8 on 2021-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibrate', '0003_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=24, unique=True, verbose_name='Slug'),
        ),
    ]
