# Generated by Django 3.2.8 on 2021-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibrate', '0005_auto_20211029_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_members',
            field=models.ManyToManyField(blank=True, related_name='room', to='vibrate.RoomMember'),
        ),
    ]
